---
name: MUsim
channels:
  - conda-forge
  - pytorch
dependencies:
  - colorlover
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - python-kaleido
  - python=3.12
  - pytorch-gpu
  - scikit-learn
  - scipy
  - pip:
      - git+https://github.com/skjerns/mat7.3.git
      - lindi
      - ndx_pose
      - neuroconv[openephys, dandi]
      - pynwb