Data:
  dataset_type: openephys
  openephys_experiment_id: 0
  openephys_stream_id: 0
  binary_sampling_rate:
  binary_num_channels:
  binary_dtype: int16
  emg_recordings:
  - 1
  - 4
  - 5
  emg_passband:
  - 250
  - 5000
  time_range:
  - 0
  - 0
  repo_folder: /home/smoconn/git/EMUsort
  session_folder: 
    /snel/share/data/rodent-ephys/open-ephys/treadmill/sean-pipeline/godzilla/session20221116/2022-11-16_16-19-28_myo
Sorting:
  output_folder: 
    /snel/share/data/rodent-ephys/open-ephys/treadmill/sean-pipeline/godzilla/session20221116/2022-11-16_16-19-28_myo
  GPU_to_use:
  - 1
  - 2
  - 3
  - 4
  num_KS_jobs: 25
  do_KS_param_gridsearch: true
  gridsearch_KS_params:
    Th:
    - - 9
      - 8
    - - 10
      - 4
    - - 7
      - 3
    - - 5
      - 2
    - - 2
      - 1
    spkTh:
    - - 6
      - 9
      - 12
      - 15
    - - 6
      - 9
      - 12
    - - 3
      - 6
      - 9
    - - 6
      - 9
    - - 6
  sorted_folder: 
    /snel/share/data/rodent-ephys/open-ephys/treadmill/sean-pipeline/godzilla/session20221116/2022-11-16_16-19-28_myo/sorted_g0_2022-11-16_16-19-28_myo_wkr05
Group:
  emg_chan_list:
  - - 1
    - 2
    - 4
    - 5
    - 12
    - 13
    - 14
    - 15
  remove_bad_emg_chans:
  - false
KS:
  remove_chan_delays: true
  remove_spike_outliers: true
  batch_size: 60000
  nblocks: 0
  do_CAR: false
  invert_sign: false
  nt: 61
  artifact_threshold:
  nskip: 2
  whitening_range: 32
  binning_depth: 5
  sig_interp: 20
  nt0min:
  dmin:
  dminx: 32
  min_template_size: 10
  template_sizes: 5
  nearest_chans: 8
  nearest_templates: 8
  templates_from_data: true
  n_templates: 9
  n_pcs: 9
  acg_threshold: 0.2
  ccg_threshold: 0.25
  cluster_downsampling: 20
  cluster_pcs: 64
  duplicate_spike_bins: 15
  do_correction: false
  keep_good_only: false
  save_extra_kwargs: true
  skip_kilosort_preprocessing: false
  scaleproc:
  torch_device: cuda:2
  Th_universal: 10
  Th_learned: 4
  Th_single_ch:
  - 6
  - 9
  - 12
  - 15
SI:
  chunk_duration: 60s
  max_concurrent_tasks: 2
num_chans: 8
sort_type: emu
emg_chans_used:
- CH2
- CH3
- CH5
- CH6
- CH13
- CH14
- CH15
- CH16
emg_chan_noise:
- 4.04750394821167
- 5.493041038513184
- 4.336611270904541
- 4.04750394821167
- 8.673222541809082
- 5.493041038513184
- 4.914826393127441
- 4.62571907043457
Results:
  snr_scores:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.9999990818373363
  - 1.0
  - 0.9999999999999999
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.9999999999077515
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.9999999999958008
  - 1.0
  firing_rate_validity_scores:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 9.528496524847309e-21
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  type_I_scores:
  - 1.0
  - 0.0
  - 0.3234051018186125
  - 0.32667500594479904
  - 0.0
  - 0.7004987184635248
  - 0.0
  - 0.940493832661245
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.9136084011623498
  - 1.0
  - 0.0
  - 0.7107324577388708
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.9661199824140594
  - 0.9515913909602417
  - 0.0
  - 0.6423748217986716
  type_II_scores:
  - 0.7124858112242431
  - 0.7736001878497677
  - 0.926484620745886
  - 0.9257009968808111
  - 0.9941400786948739
  - 0.9427800139093805
  - 0.9222092567306017
  - 0.9979229114369754
  - 0.8496140158844473
  - 0.6274568225765081
  - 0.0
  - 0.7091586549023743
  - 0.8422907026823832
  - 0.0
  - 0.7702886239859037
  - 0.9250209855066495
  - 0.7830909069743847
  - 0.9188664836861783
  - 0.9846239676894349
  - 0.7848342409316069
  - 0.2849735928259803
  - 0.9972530036124296
  - 0.9986544695878488
  - 0.9815037897333486
  - 0.9969609459638208
  emusort_scores:
  - 0.7124858112242431
  - 0.0
  - 0.29962985310570184
  - 0.30240337865914535
  - 0.0
  - 0.6604161915365452
  - 0.0
  - 0.9385403436778291
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.7695238621915642
  - 0.0
  - 0.0
  - 0.6574424384891734
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.2849735928259803
  - 0.9634660543124084
  - 0.9503109958037634
  - 0.0
  - 0.6404226100037445
