Data:
  dataset_type: openephys
  openephys_experiment_id: 0
  openephys_stream_id: 0
  binary_sampling_rate:
  binary_num_channels:
  binary_dtype: int16
  emg_recordings:
  - 0
  emg_passband:
  - 250
  - 5000
  time_range:
  - 1200
  - 1800
  repo_folder: /home/smoconn/git/EMUsort
  session_folder: 
    /snel/share/data/rodent-ephys/open-ephys/monkey/sean-pipeline/session20231202/2022-12-02_10-14-45_myo
Sorting:
  output_folder: 
    /snel/share/data/rodent-ephys/open-ephys/monkey/sean-pipeline/session20231202/2022-12-02_10-14-45_myo
  GPU_to_use:
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
  - 2
  - 1
  - 0
  num_KS_jobs: 25
  do_KS_param_gridsearch: true
  gridsearch_KS_params:
    Th:
    - - 9
      - 8
    - - 10
      - 4
    - - 7
      - 3
    - - 5
      - 2
    - - 2
      - 1
    spkTh:
    - - 6
      - 9
      - 12
      - 15
      - 18
    - - 6
      - 9
      - 12
      - 15
    - - 6
      - 9
      - 12
    - - 6
      - 9
    - - 6
  sorted_folder: 
    /snel/share/data/rodent-ephys/open-ephys/monkey/sean-pipeline/session20231202/2022-12-02_10-14-45_myo/sorted_g0_2022-12-02_10-14-45_myo_wkr08
Group:
  emg_chan_list:
  - - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  remove_bad_emg_chans:
  - true
KS:
  remove_chan_delays: true
  remove_spike_outliers: true
  batch_size: 60000
  nblocks: 0
  do_CAR: false
  invert_sign: false
  nt: 121
  artifact_threshold:
  nskip: 1
  whitening_range: 32
  binning_depth: 5
  sig_interp: 20
  nt0min:
  dmin:
  dminx: 32
  min_template_size: 10
  template_sizes: 5
  nearest_chans: 10
  nearest_templates: 16
  templates_from_data: true
  n_templates: 9
  n_pcs: 9
  acg_threshold: 0.2
  ccg_threshold: 0.25
  cluster_downsampling: 20
  cluster_pcs: 64
  duplicate_spike_bins: 15
  do_correction: false
  keep_good_only: false
  save_extra_kwargs: true
  skip_kilosort_preprocessing: false
  scaleproc:
  torch_device: cuda:1
  Th_universal: 10
  Th_learned: 4
  Th_single_ch:
  - 6
  - 9
SI:
  chunk_duration: 20s
  max_concurrent_tasks: 13
num_chans: 16
sort_type: emu
emg_chans_used:
- CH17
- CH18
- CH19
- CH20
- CH21
- CH22
- CH23
- CH24
- CH25
- CH26
- CH27
- CH28
- CH29
- CH30
- CH31
- CH32
emg_chan_noise:
- 3.1801817417144775
- 3.1801817417144775
- 4.04750394821167
- 2.312859535217285
- 2.8910741806030273
- 2.6019668579101562
- 2.312859535217285
- 2.312859535217285
- 2.023751974105835
- 2.023751974105835
- 1.4455370903015137
- 1.7346445322036743
- 2.023751974105835
- 2.023751974105835
- 1.7346445322036743
- 2.6019668579101562
Results:
  snr_scores:
  - 0.999999999999994
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.07327703589920675
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.9476975505157401
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.2435309453528185
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.905151276152799
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.9753866716437513
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.9999999999999863
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.8549082974528
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.999882328252801
  firing_rate_validity_scores:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  type_I_scores:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.7770985561920026
  - 1.0
  - 0.5807685729371563
  - 1.0
  - 1.0
  - 0.8189729352709978
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  - 0.8513821237898753
  - 1.0
  - 0.7370029144726781
  - 0.5852672928468373
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 0.0
  - 0.3464937549037097
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 0.7908161723955653
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  type_II_scores:
  - 0.4590210002382978
  - 0.6058673165718734
  - 0.4277327000468162
  - 0.46493301966919126
  - 0.7633989630709871
  - 0.8261556030093954
  - 0.9932573591085267
  - 0.5328458185183852
  - 0.3
  - 0.7309741387076222
  - 0.8274139287925159
  - 0.9964304883283469
  - 0.7897103934892656
  - 0.0
  - 0.0
  - 0.0
  - 0.780743023159359
  - 0.4812367742468616
  - 0.8576790082052157
  - 0.7881588747600756
  - 0.7492298695782779
  - 0.8960380315219377
  - 0.7694657923301708
  - 0.7534300768880219
  - 0.9645906628338436
  - 0.8377150272410249
  - 0.6653209541534375
  - 0.8150498146566204
  - 0.4364189859721407
  - 0.7764177328506108
  - 0.5579295297569822
  - 0.8967703582997462
  - 0.6644797920947925
  - 0.8975740203942032
  - 0.47135084162364427
  - 0.5121461764678964
  - 0.561153732623894
  - 0.0
  - 0.5291403774813589
  - 0.9993222649511936
  - 0.8647426134652735
  - 0.78289067963866
  - 0.46282412714410637
  - 0.6813338989091285
  - 0.722031310940254
  - 0.0
  - 0.5234273187342169
  - 0.38333333333333336
  - 0.8262121892062012
  - 0.7472673061992036
  - 0.6250224439138153
  - 0.8313329227381234
  - 0.7630608502619936
  - 0.0
  - 0.5235777912606143
  - 0.806205723859834
  - 0.7864361872984624
  - 0.5520182405373947
  - 0.5605565986846346
  - 0.4137098498245967
  - 0.44682318056975484
  - 0.5957078880656299
  - 0.5577487851591795
  - 0.5620002820541034
  - 0.9908486307825196
  - 0.5922799673226775
  - 0.7884774853222509
  - 0.5636109568890855
  - 0.5933831485670381
  - 0.7508097865461183
  - 0.7597478681001931
  - 0.5917858850264144
  - 0.0
  - 0.0
  - 0.7238162187538504
  - 0.6840457909527866
  - 0.28763976099575944
  - 0.7292718571109237
  - 0.5553749143565191
  - 0.7496954575364536
  - 0.8991498695954622
  emusort_scores:
  - 0.0
  - 0.0
  - 0.0
  - 0.46493301966919126
  - 0.593236232000936
  - 0.8261556030093954
  - 0.04227005300273981
  - 0.5328458185183852
  - 0.3
  - 0.5986480359845708
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.8576790082052157
  - 0.6710243766770716
  - 0.7492298695782779
  - 0.6603826407100295
  - 0.45034316121532575
  - 0.0
  - 0.0
  - 0.0
  - 0.6653209541534375
  - 0.0
  - 0.4364189859721407
  - 0.7764177328506108
  - 0.0
  - 0.8967703582997462
  - 0.0
  - 0.0
  - 0.47135084162364427
  - 0.5121461764678964
  - 0.0
  - 0.0
  - 0.0
  - 0.3377363393505576
  - 0.8647426134652735
  - 0.0
  - 0.46282412714410637
  - 0.6813338989091285
  - 0.722031310940254
  - 0.0
  - 0.5234273187342169
  - 0.38333333333333336
  - 0.0
  - 0.7472673061992036
  - 0.6250224439138153
  - 0.657431519946181
  - 0.7630608502619936
  - 0.0
  - 0.5235777912606143
  - 0.806205723859834
  - 0.7864361872984624
  - 0.5520182405373947
  - 0.5605565986846346
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.5922799673226775
  - 0.7884774853222509
  - 0.0
  - 0.5933831485670381
  - 0.7508097865461183
  - 0.0
  - 0.5917858850264144
  - 0.0
  - 0.0
  - 0.7238162187538504
  - 0.6840457909527866
  - 0.0
  - 0.7292718571109237
  - 0.5553749143565191
  - 0.0
  - 0.0
